webapp:
  build: ./docker-mold-webapp
  dockerfile: Dockerfile.debug
  environment:
    - HOST_NAME=localhost
    - HOST_PORT=8080
    - BRANCH=master
  ports:
   - "8080:80"
  links:
    - api
    - vt
    - ldf
api:
  build: ./docker-mold-api
  dockerfile: Dockerfile.debug
  environment:
    - BRANCH=sparql_post
  links:
    - vt
vt:
  image: mold/docker-virtuoso:7.2.4.2
  volumes:
    - ./mold-virtuoso:/mnt/graphs
  ports:
    - "9000:9000"
ldf:
  image: linkeddatafragments/server.js
  command: /mnt/ldf/mold-config.json 3000 4
  volumes:
    - ./docker-mold-ldf:/mnt/ldf
  ports:
    - "3000:3000"
  links:
    - vt
