webapp:
  image: mold/mold_webapp
  environment:
    - HOST_NAME=localhost
    - HOST_PORT=80
  ports:
   - "80:80"
  links:
   - api
   - vt
   - ldf
api:
  image: mold/mold_api
  links:
    - vt
vt:
  image: mold/docker-virtuoso:7.2.4.2
  volumes:
    - ./mold-virtuoso:/mnt/graphs
ldf:
  image: linkeddatafragments/server.js
  command: /mnt/ldf/mold-config.json 3000 4
  volumes:
    - ./docker-mold-ldf:/mnt/ldf
  links:
    - vt
