# Debian OS
FROM debian

# Maintainer
MAINTAINER zorino <maximilien1er@gmail.com>

# Install intermine dependencies
RUN apt-get update \
 && apt-get install -y curl git \
 && gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 \
 && \curl -L https://get.rvm.io | bash -s stable \
 && apt-get clean all

COPY mold-api-entry.debug.sh /opt/mold-api-entry.sh

EXPOSE 9393

ENTRYPOINT ["/opt/mold-api-entry.sh"]
