# Nginx web server
FROM nginx

# Maintainer
MAINTAINER zorino <maximilien1er@gmail.com>

# Install intermine dependencies
RUN apt-get update \
 && apt-get install -y curl git \
 && apt-get clean all

COPY nginx-entry.debug.sh /usr/bin/nginx-entry.sh
COPY nginx.conf /etc/nginx/nginx.conf

ENV NGINX_PORT=80

ENTRYPOINT ["nginx-entry.sh"]
